# Variables
@Authorization = Bearer {{token}}
@customerId = customer_id

# Create Customer
POST {{baseUrl}}/api/v1/customers HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

{}

###

# Get Customers
GET {{baseUrl}}/api/v1/customers HTTP/1.1
Accept: application/json
Authorization: {{Authorization}}

###

# Get Customer Details
GET {{baseUrl}}/api/v1/customers/{{customerId}} HTTP/1.1
Accept: application/json
Authorization: {{Authorization}}

###

# Update Customer Details
PATCH {{baseUrl}}/api/v1/customers/{{customerId}} HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

{}

###

# Delete Customer
DELETE {{baseUrl}}/api/v1/customers/{{customerId}} HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

###
