# Variables
@Authorization = Bearer {{token}}
@roleId = role_id

# Create Role
POST {{baseUrl}}/api/v1/roles HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

{}

###

# Get Roles
GET {{baseUrl}}/api/v1/roles HTTP/1.1
Accept: application/json
Authorization: {{Authorization}}

###

# Get Role Details
GET {{baseUrl}}/api/v1/roles/{{roleId}} HTTP/1.1
Accept: application/json
Authorization: {{Authorization}}

###

# Update Role Details
PATCH {{baseUrl}}/api/v1/roles/{{roleId}} HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

{}

###

# Delete Role
DELETE {{baseUrl}}/api/v1/roles/{{roleId}} HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

###
