# Variables
@Authorization = Bearer {{token}}
@appId = client_app_id


# Create Client App
POST {{baseUrl}}/api/v1/apps/register HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

{
  "name": "Test App",
  "organizationId": "organization-67c316578dfc4a3141e96c87"
}

###

# Get Client Apps
GET {{baseUrl}}/api/v1/apps?q=test&include=developer,organization HTTP/1.1
Accept: application/json
Authorization: {{Authorization}}

###

# Get Client App Details
GET {{baseUrl}}/api/v1/apps/{{appId}} HTTP/1.1
Accept: application/json
Authorization: {{Authorization}}

###

# Update Client App Details
PATCH {{baseUrl}}/api/v1/apps/{{appId}} HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

{}

###

# Delete Client App
DELETE {{baseUrl}}/api/v1/apps/{{appId}} HTTP/1.1
Content-Type: application/json
Authorization: {{Authorization}}

###
