# Variables
@baseUrl = http://localhost:3000
@Authorization = Bearer your_access_token
@csrfToken = you_csrf_token

# Signup as Developer
POST {{baseUrl}}/api/v1/auth/developer/signup HTTP/1.1
Content-Type: application/json

{
    "email": "your@email.com",
    "password": "your password",
    "name": "Firstname Lastname"
}

###

# Developer Login
POST {{baseUrl}}/api/v1/auth/developer/signup HTTP/1.1
Content-Type: application/json

{
    "email": "your@gmail.com",
    "password": "your password",
}

###

# Developer Refresh Auth (when access Token expires
POST {{baseUrl}}/api/v1/auth/developer/refresh-token
Content-Type: application/json

{
  "userId": "your userId"
}

###

# View Developer profile
GET {{baseUrl}}/api/v1/auth/developer/me HTTP 1/1
Accept: application/json
Authorization: {{Authorization}}

